import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { NavbarDemo } from "@/components/NavBar";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const [dark,setDark] = useState('')
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
      <NavbarDemo />
        {children} 
        </body>
      {/* page.tsx k andr jo hoga woh as child ishme aayega ( default ) */}
    </html>
  );
}
